#!/bin/bash
#
# Maintainer script for publishing releases.

set -e

js_version=$(node -p "require('./package.json').version")
deb_version=$(dpkg-parsechangelog -S Version)

# ensure that javascript package version matches debian package version
# debian package is allowed to have "+*" suffix and still be considered
# the same version (i.e. only the debian packaging changed and not the
# javascript package)
if [[ "${js_version}" != "${deb_version/+*/}" ]]; then
    echo "version mismatch - js: ${js_version} != deb: ${deb_version}"
    exit 1
fi

gbp buildpackage --git-tag-only
debuild
debrelease
git push --tags
